
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dodomiysjrrpdwzpplrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZG9taXlzanJycGR3enBwbHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTY2NTYsImV4cCI6MjA2NTU3MjY1Nn0.0lX97XUzYq9bZXMLvDtEucflnghPo7HarbxGQKXvjMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
